blog/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = "blog"


urlpatterns = [
    path("", views.home, name="home"),
    path("post/<slug:slug>/", views.detail, name="detail"),
    path("archives/", views.archives, name="archives"),
    path("about/", views.about, name="about"),
    path(
        "tag/<slug:tag_slug>/<int:pk>/",
        views.similar_posts_by_tag,
        name="search_tag",
    ),
    path("search/", views.blog_search, name="search"),
    path("feed/", views.RSSFeed(), name="RSS"),
]

core/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from blog.sitemap import HomePageSiteMap
from blog.sitemap import PostSiteMap
from blog.sitemap import StaticSiteMap


app_name = "core"


sitemaps = {
    "posts": PostSiteMap,
    "static": StaticSiteMap,
    "home": HomePageSiteMap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitsitemap",
    ),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.html import mark_safe
from django.utils.html import format_html

from . import meta
from .templatetags.markdownify import markdown

from simplemde.fields import SimpleMDEField
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(status="draft")


class Post(models.Model):

    STATUS_CHOICE = (
        ("draft", "Draft"),
        ("published", "Published"),
    )

    title = models.CharField(max_length=100)
    content = SimpleMDEField(blank=True, null=True)
    slug = models.SlugField("Slug")
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICE, default="draft"
    )

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})

    @property
    def summary(self):
        subs = '<a class="small" href="{}"> read more...</a>'.format(
            self.get_absolute_url()
        )

        metas, _ = meta.parse(self.content)
        if metas:
            metas["summary"] = metas["summary"][::-1].replace(
                "...", subs[::-1], 1
            )[::-1]
        return metas

    @property
    def body(self):
        _, content = meta.parse(self.content)
        return mark_safe(markdown(content))

    def __str__(self):
        return "{}".format(self.title)

    class Meta:
        ordering = ["-created"]

blog/views.py
from django.contrib.syndication.views import Feed
from django.core import serializers
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import get_list_or_404
from django.shortcuts import redirect
from django.shortcuts import render

from .models import Post
from .templatetags.markdownify import markdown


def home(request):
    if request.user.is_authenticated:
        posts = Post.objects.all()
    else:
        posts = Post.published.all()

    paginator = Paginator(posts, 5)
    page = request.GET.get("page")

    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.paginator(paginator.num_pages)
    return render(request, "home.html", {"post_list": post_list})


def similar_posts_by_tag(request, tag_slug, pk):
    post = Post.objects.get(pk=pk)
    post_tags_ids = post.tags.values_list("id", flat=True)
    if request.user.is_authenticated:
        similar_posts = Post.objects.filter(tags__in=post_tags_ids).exclude(
            id=post.id
        )
        similar_posts = similar_posts.annotate(
            same_tags=Count("tags")
        ).order_by("-same_tags", "-publish")[:4]
    else:
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(
            id=post.id
        )
        similar_posts = similar_posts.annotate(
            same_tags=Count("tags")
        ).order_by("-same_tags", "-publish")[:4]
    return render(request, "tag.html", {"post_list": similar_posts})


def detail(request, slug):
    post = Post.objects.get(slug=slug)
    tags = post.tags.all()
    return render(request, "post.html", {"post": post, "tags": tags})


def about(request):
    return render(request, "about.html")


def archives(request):
    if request.user.is_authenticated:
        post_list = Post.objects.all()
    else:
        post_list = Post.published.all()
    return render(
        request, "archives.html", {"post_list": post_list, "error": False}
    )


def blog_search(request):
    if "search" in request.GET:
        search = request.GET["search"]
        if not search:
            return render(request, "home.html")
    else:
        post_list = get_list_or_404(
            Post.objects.filter(title__icontains=search)
        )
        if len(post_list) == 0:
            return render(
                request,
                "archives.html",
                {"post_list": post_list, "error": True},
            )
        else:
            return render(
                request,
                "archvies.html",
                {"post_list": post_list, "error": False},
            )
    return redirect("/")


class RSSFeed(Feed):
    title = "RSS feed - Articles"
    link = "/feeds/posts/"
    description = "RSS feed - Blog Posts"

    def items(self):
        return get_list_or_404(Post.published.all())

    def items_title(self, item):
        return item.title

    def item_pubdate(self, item):
        return item.created_at

    def item_description(self, item):
        return markdown(item.content)

blog/templates/about.html
{% extends "base.html" %}
{% block content %}
    <div class="content-subhead">Aboute Me</div>
    <div class="well-lg">
        <p class="text-justify">
            Hello World!
        </p>
    </div>
{% endblock %}

blog/templates/aboutme.html
{% extends "base.html" %}
{% load custom_markdown %}
{% load media_responsive %}

{% block content %}
    <div class="content-subhead">Aboute Me</div>
    <div class="well-lg">
        <p class="text-justify">
            {{ description.description|custom_markdown|media_responsive:400}}
        </p>
    </div>
{% endblock %}

blog/templates/archives.html
{% extends "base.html" %}
{% block content %}
<div class="content-subhead">All posts in archive</div>
{% if error %}
    <p>No related posts</p>
{% else %}
    {% for post in post_list %}
        <section>
            <header>
                <h2>
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h2>
                <p class="">
                Published:
                    <a href="#">
                        {{ post.created|date:'Y /m /d'}}
                    </a> &nbsp;&nbsp;
                Tag:
                    {% for tag in post.tags.all %}                            
                        <a href="{% url 'blog:search_tag' tag=tag post=post.pk %}">
                            {{ tag }}
                        </a>
                    {% endfor %}
                </p>
            </header>
        </section>
        <hr>
    {% endfor %}
{% endif %}
{% endblock %}

blog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
        <meta name="description" content="André Santos Blog">
        <!-- SEO -->
        <meta property="og:title" content="André Santos Blog">
        <meta property="og:description" content="André Santos Blog. Blog pessoal, anotações.">
        <meta property="og:url" content="https://andreztz.pythonanywhere.com">
        <meta property="og:image" content="{% static 'images/image.jpg' %}">
        <meta property="og:type" content="website">
        <meta property="og:site_name" content="André P. Santos Blog">
        <title>{% block title %} André Santos Blog {% endblock %}</title>
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'ico/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="96x96" href="{% static 'ico/favicon-96x96.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'ico/favicon-16x16.png' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/pygments.css' %}">
        <link rel="stylesheet" href="{% static 'css/css.css' %}">
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css">
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date(); a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
            ga('create', 'UA-75331741-1', 'auto');
            ga('send', 'pageview');
        </script>
    </head>
    <body class="container-fluid">
        <main class="row">
            <header class="col-xs-12 col-md-3 column-left">
                {% include "sidebar.html" %}
            </header>
            <section class="col-xs-12 col-md-9 column-right">
                {% block content %}{% endblock %}
            </section>
            <footer>
                {% include "footer.html" %}
            </footer>
        </main>
        <script>
            var $top = $('.go-top');
            // Show or hide the sticky footer button
            $(window).scroll(function () {
                if ($(this).scrollTop() > 200) {
                    $top.fadeIn(200);
                } else {
                    $top.fadeOut(200);
                }
            });
            // Animate the scroll to top
            $top.click(function (event) {
                event.preventDefault();
                $('html, body').animate({ scrollTop: 0 }, 300);
            });
            // Makes sure that the href="#" attached to the <a> elements
            // don't scroll you back up the page.
            $('body').on('click', 'a[href="#"]', function (event) {
                event.preventDefault();
                $(this).scrollTop();
            });
        </script>
        <script src="{% static 'js/app.js' %}"></script>
    </body>
</html>

blog/templates/comments.html
<div class="ds-thread" data-thread-key="{{ post.id }}" data-title="{{ post.title }}"
    data-url="{{ post.get_absolute_url }}"></div>

<script type="text/javascript">
// var duoshuoQuery = {short_name:"#"}; //andreztz
//     (function() {
//         var ds = document.createElement('script');
//         ds.type = 'text/javascript'; ds.async = true;
//         ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
//         ds.charset = 'UTF-8';
//         (document.getElementsByTagName('head')[0] 
//          || document.getElementsByTagName('body')[0]).appendChild(ds);
//     })();
</script>

blog/templates/footer.html
<div class="col-xs-12 col-md-9 col-md-offset-3 column-right">
    <small><p class="text-center">© André Santos – Boa Sorte!</p><small>
</div>

blog/templates/home.html
{% extends "base.html" %}
{% load media_first %}
{% load media_responsive %}
{% block content %}
<div class="content-subhead">Latest Posts</div>
{% for post in post_list %}
    <header>
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
    </header>
    <div class="text-justify">
        <p>
            {% if post.summary %}
            <img src="{{ post.summary.image | safe }}" alt="">
            <p>{{ post.summary.summary | safe }}</p>
            {% else %}
            {{ post.body | truncatewords_html:50 }}
            {% endif %}
        </p>
    </div>
    <p class=" small post-meta">
        Published:
        <a href="#">
            {{ post.created|date:"D d F Y"}}
        </a> &nbsp;&nbsp;
        Tags:
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:search_tag' tag_slug=tag.slug pk=post.pk %}">
                {{ tag }}
            </a>
        {% endfor %}
    </p>
    <hr>
{% empty %}
    <p>Sorry, no article in this Blog!!.</p>
{% endfor %}
{% if post_list.object_list and post_list.paginator.num_pages > 1 %}
    <div>
        <ul class="pagination">
            {% if post_list.has_previous %}
            <li>
                <a href="?page={{ post_list.previous_page_number }}">❮</a>
            </li>
            {% endif %}
            {% if post_list.has_next %}
            <li>
                <a href="?page={{ post_list.next_page_number }}">❯</a>
            </li>
            {% endif %}
        </ul>
    </div>
{% endif %}
    <a href="#" class="go-top">Go Top</a>
{% endblock %}

blog/templates/post.html
{% extends "base.html" %}
{% block content %}
    <header class="content-subhead">
        edited &rarr;
        <a class="">
            {{ post.updated | date:'d/m/Y' }}
        </a>
    </header>
    <article class="article">
        <h1>{{ post.title }}</h1>
        <p class="text-justify">{{ post.body }}</p>
    </article>
    <hr>
    <ul class="tags">
        {% for tag in post.tags.all %}
        <li>
            <a class="tag" href="{% url 'blog:search_tag' tag.slug post.pk %}">{{ tag }}</a>
        </li>
        {% endfor %}
    </ul>
    <a href="#">Published: {{ post.created|date:"D d F Y"}}</a>
    {% include "comments.html" %}
    <a href="#" class="go-top">Go Top</a>
{% endblock %}

blog/templates/sidebar.html
<div class="column-left-menu">
    <img src="https://s.gravatar.com/avatar/4d420075a242b2c9b470b23ec2a914a0?s=600" alt=""
        class="img-responsive img-circle image-profile"  width="600" height="600"/>
    <h1 class="blog-title text-center">
        <a href="{% url 'blog:home' %}">André Santos Blog</a>
    </h1>
    <br>
    <div class="menu-sidebar text-center">
        <div class="btn-burguer">
            <div>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </div>
        </div>
        <ul class="dropdown">
            {% if request.get_full_path != '/' %}
            <li>
                <a href="{% url 'blog:home' %}">Home</a>
            </li>
            {% endif %}
            {% if  request.get_full_path != '/about/' %}
            <li>
                <a href="{% url 'blog:about' %}">About Me</a>
            </li>
            {% endif %}
            {% if  request.get_full_path != '/archives/' %}
            <li>
                <a href="{% url 'blog:archives' %}">Archive</a>
            </li>
            {% endif %}
            <li>
                <a href="{% url 'blog:RSS' %}" target="_blank">RSS</a>
            </li>
        </ul>
    </div>
    <div class="social social-icons text-center">
        <a href="https://www.facebook.com/ztzandre" target="_blank">
            <i id="social-btn" class="fa fa-facebook fa-3x"></i>
        </a>
        <a href="https://github.com/andreztz" target="_blank">
            <i id="social-btn" class="fa fa-github fa-3x"></i>
        </a>
        <a href="https://www.youtube.com/channel/UCAwZjRyaUvoVu2thZBoGO8w" target="_blank">
            <i id="social-btn" class="fa fa-youtube fa-3x"></i>
        </a>
        <a href="https://plus.google.com/u/0/+AndréSantosztz" target="_blank">
            <i id="social-btn" class="fa fa-google-plus fa-3x"></i>
        </a>
        <a href="https://twitter.com/ztzandre" target="_blank">
            <i id="social-btn" class="fa fa-twitter fa-3x"></i>
        </a>
    </div>
</div>

blog/templates/tag.html
{% extends "base.html" %}
{% block pagetitle %}
    {% for post in post_list %}
        <title>{{ post.title }} category</title>
    {% endfor %}
{% endblock %}
{% block content %}
    <div class="content-subhead">All posts</div>
    {% for post in post_list %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <br>
        <p class="small post-meta">
            published：
                <a class="">
                    {{ post.created | date:'Y/m/d' }}
                </a>
                &nbsp;&nbsp;
            edited：
                <a class="">
                    {{ post.updated | date:'Y/m/d' }}
                </a>
                &nbsp;&nbsp;
            tags：
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:search_tag' tag.slug post.pk %}">{{ tag }}</a>
            {% endfor %}
        </p>
        <br>
    {% empty %}
        <li>Sorry, there are no similar posts yet!!.</li>
    {% endfor %}
  </div>
  <a href="#" class="go-top">Go Top</a>
{% endblock %}